DROP DATABASE IF EXISTS ChefItUp;

CREATE DATABASE ChefItUp;

USE ChefItUp;

CREATE TABLE User(
    userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    type  VARCHAR(255) NOT NULL,
    registrationDate DATETIME NOT NULL
);


